name: Build/Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build:${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'windows-latest' && 'win' || 'mac') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: build-linux
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.tar.gz
          retention-days: 1

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: build-windows
          path: dist/*.exe
          retention-days: 1
